build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
checks:
  php:
    psr2_switch_declaration: true
    psr2_class_declaration: true
    no_short_open_tag: true
    deprecated_code_usage: true
    code_rating: true
tools:
  php_analyzer: true
  php_code_sniffer:
    config:
      standard: PSR2
